apiVersion: v1
kind: Service
metadata:
  name: django-svc
  labels:
    app: django
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: django
    tier: frontend
  type: LoadBalancer
