apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wordpress-mydb-read
  labels:
    app: wordpress-mydb
spec:
  ports:
  - name: wordpress-mysql
    port: 3306
    targetPort: 3306
  selector:
    app: wordpress-mydb
  type: ClusterIP