apiVersion: v1
kind: ConfigMap
metadata:
  namespace: wordpress
  name: wordpress-mydb-config
  labels:
    app: wordpress-mydb
data:
  master.cnf: |
    [mysqld]
    log-bin
  slave.cnf: |
    [mysqld]
    super-read-only
