apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: example-ingress
  namespace: webserver
  annotations:  
    nginx.ingress.kubernetes.io/rewrite-target: /$1  
spec:
#  defaultBackend:
#    service:
#      name: web-svc
#      port:
#        number: 8001
  ingressClassName: nginx
  rules:
    - host: hello.example.com
      http:
        paths: 
          - path: / 
            pathType: Prefix 
            backend:
              service:  
                name: web-svc
                port:
                  number: 80
