controller:
  tag: "lts-jdk11"
  serviceType: LoadBalancer
  installPlugins:
  - kubernetes
  - workflow-aggregator
  - git
  - configuration-as-code
  - pipeline-stage-view
  adminPassword: "1234"

persistence:
  storageClass: ""
